[tool.poetry]
name = "tiny-brainfuck"
version = "0.1.0"
description = ""
authors = ["tiny-brainfuck"]
readme = "README.md"
packages = [{include = "tiny_brainfuck"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
